### PR TITLE
transition to Django 1.5

### PR DESCRIPTION
**Pull request by ghost**
I like to use django-live-profiler... when i passed to Django 1.5, it will break for 2 reasons :
1. Django 1.5 does not have the compiler. "empty_iter" function, they directly use

``` python
"iter([])"
```
1. template tags like {% url name %} change to {% url "name" %} on Django 1.3 with {% load url from future %} and was definitive on Django 1.5.

If you want to cover old Django version, i think the best way is firstly make unit tests and use tox or/and travis.ci...

precision : i test my patch on Django 1.4 and 1.5...

### CODE REVIEW

**Comment by atereshkin** [comment]
Thanks! 

Before I merge, would you care to look into making it backward-compatible with 1.3? For the templates I believe you just need to add "{% load url from future %}", but the instrumentation needs to be checked (though it might just work as is). 

No problem if not though - will do it myself. Just a bit busy right now.

**Comment by rayhatfield** [comment]
Ha. Was about to suggest the same changes. Thanks for your work on this.

**Comment by brycenesbitt** [comment]
I'd like to see this pulled also.  I get:

  File "PycharmProjects/virtualenvs/obviously/local/lib/python2.7/site-packages/profiler/instrument.py",
   ImportError: cannot import name empty_iter

From the line "django.db.models.sql.compiler import SQLCompiler, empty_iter"
And 'url' requires a non-empty first argument. The syntax changed in Django 1.5, see the docs.

**Comment by JustinSGray** [comment]
I just ran into this issue as well... any plans to pull this in?

**Comment by chrisspen** [comment]
Just upgraded to 1.5. Found this bug is a blocker. Would love to see this fixed.

**Comment by atereshkin** [comment]
OK folks, you win. Guess we'll have to leave implementing 1.4 compatibility to whoever needs it.

**Comment by aniketbehera** [comment]
Any update on this please. I get the same error. Thanks

**Comment by LucianU** [comment]
Same here. Updates would be welcome. What I mean is that it looks like this recent merge hasn't been released on PyPI.

**Comment by MRigal** [comment]
True @atereshkin don't you want to make a release tag here, this would make it easy to get a new version from PyPI

**Comment by MRigal** [comment]
And just for info, adding {% load url from future %} fixes the bug on 1.3 - 1.4, indeed this should be added also

**Comment by ghost** [comment]
Still running this error with 1.5 when installing via pip.

from django.db.models.sql.compiler import SQLCompiler, empty_iter
ImportError: cannot import name empty_iter

pip freeze | grep live
django-live-profiler==0.0.9

**Comment by illagrenan** [comment]
Same error on Django 1.6:

```
File "C:\Users\xx\.virtualenvs\xx\lib\site-packages\profiler\instrument.py", line 3, in <module>
    from django.db.models.sql.compiler import SQLCompiler, empty_iter
ImportError: cannot import name empty_iter
```

**Comment by tapia** [comment]
Yep, same error with 1.6 here. Any news on this?

**Comment by dhirajt** [comment]
yep still getting this error.

**Comment by marjoripomarole** [comment]
Help! Same error here on Django 1.6 :)

**Comment by tclancy** [comment]
It looks like the version on Pypi (which you'd get if you just run `pip install django-live-profiler`) is out-of-date. You can install the current version with `pip install -e git+git://github.com/InviteBox/django-live-profiler.git#egg=django-live-profiler`. That seems to work for me on Django 1.5 (or at least gets around the empty_iter error.

**Pull request merged**
